<template>
  <GlassCard class="relative overflow-hidden">
    <div
      class="absolute right-0 top-0 h-64 w-64 rounded-full bg-blue-500/10 blur-3xl"
    />

    <div class="relative">
      <div class="flex items-center gap-4">
        <div
          class="flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-500/10"
        >
          <Sparkles class="h-7 w-7 text-blue-300" />
        </div>

        <div>
          <h3 class="text-2xl font-black">
            AI Insight Generator
          </h3>

          <p
            class="mt-1 text-sm"
            :style="{ color: 'var(--text-secondary)' }"
          >
            Generate smart business recommendations
          </p>
        </div>
      </div>

      <div class="mt-8">
        <textarea
          v-model="prompt"
          placeholder="Ask PulseIQ AI about your analytics..."
          rows="5"
          class="w-full resize-none rounded-3xl border bg-transparent p-5 outline-none transition"
          :style="{
            borderColor: 'var(--border-color)',
            color: 'var(--text-primary)',
          }"
        />
      </div>

      <div class="mt-5 flex items-center justify-between">
        <p
          class="text-sm"
          :style="{ color: 'var(--text-secondary)' }"
        >
          Example: “How can I improve conversions?”
        </p>

        <button
          class="rounded-2xl bg-gradient-to-r from-blue-400 to-cyan-300 px-5 py-3 font-semibold text-black transition hover:scale-[1.02]"
          @click="generateInsight(prompt)"
        >
          Generate Insight
        </button>
      </div>

      <div
        v-if="loading"
        class="mt-8 rounded-3xl border p-6"
        :style="{
          borderColor: 'var(--border-color)',
          background: 'rgba(255,255,255,0.03)',
        }"
      >
        <div class="flex items-center gap-3">
          <div
            class="h-3 w-3 rounded-full bg-blue-400 animate-pulse"
          />

          <p class="font-medium">
            PulseIQ AI is analyzing your data...
          </p>
        </div>
      </div>

      <div
        v-if="response"
        class="mt-8 rounded-3xl border p-6"
        :style="{
          borderColor: 'var(--border-color)',
          background: 'rgba(255,255,255,0.03)',
        }"
      >
        <div class="mb-4 flex items-center gap-3">
          <div
            class="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500/10"
          >
            <Sparkles class="h-5 w-5 text-blue-300" />
          </div>

          <div>
            <p class="font-semibold">
              AI Recommendation
            </p>

            <p
              class="text-sm"
              :style="{ color: 'var(--text-secondary)' }"
            >
              Generated by PulseIQ Intelligence
            </p>
          </div>
        </div>

        <p
          class="leading-relaxed"
          :style="{ color: 'var(--text-primary)' }"
        >
          {{ response }}
        </p>
      </div>
    </div>
  </GlassCard>
</template>

<script setup>
import { ref } from 'vue'

import { Sparkles } from 'lucide-vue-next'

import GlassCard from '@/components/ui/GlassCard.vue'

import { useMockAI } from '@/composables/useMockAI'

const prompt = ref('')

const {
  loading,
  response,
  generateInsight,
} = useMockAI()
</script>